podIdentityPolicyCreate: true
podIdentityRole:
  description: "EFS Controller Default Role"
podIdentityAssociation:
  serviceAccounts:
      - ack-efs-controller
podIdentityPolicy:
   description: "EFS Role"
   policies:
     - resourceType: efs
       resourceName: "*"
       actions: 
       - "elasticfilesystem:*"