apiVersion: kro.run/v1alpha1
kind: ResultApp
metadata:
  name: result-app-demo
  namespace: default
spec:
  name: result-app-demo
  namespace: default
  image: "dogsvscats/result:latest"
  replicas: 1
  postgresEndpoint: "your-postgres-endpoint-here"
  postgresSecretName: "your-postgres-secret-name"
  service:
    enabled: true
  ingress:
    enabled: true