{{- range $key, $value := .Values.clusters }}
---
apiVersion: services.k8s.aws/v1alpha1
kind: IAMRoleSelector
metadata:
  name: {{ $key }}-namespace-config
spec:
  arn: arn:aws:iam::{{ $value }}:role/ack
  namespaceSelector:
    names:
      - {{ $key }}
{{- end }}