apiVersion: kro.run/v1alpha1
kind: VoteApp
metadata:
  name: vote-app-demo
  namespace: default
spec:
  name: vote-app-demo
  namespace: default
  image: "dogsvscats/vote:latest"
  replicas: 2
  redisEndpoint: "your-redis-endpoint-here"
  service:
    enabled: true
  ingress:
    enabled: true