apiVersion: kro.run/v1alpha1
kind: WorkerApp
metadata:
  name: worker-app-demo
  namespace: default
spec:
  name: worker-app-demo
  namespace: default
  image: "dogsvscats/worker:latest"
  replicas: 1
  redisEndpoint: "your-redis-endpoint-here"
  postgresEndpoint: "your-postgres-endpoint-here"
  postgresSecretName: "your-postgres-secret-name"