apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: worker-app.kro.run
spec:
  schema:
    apiVersion: kro.run/v1alpha1
    kind: WorkerApp
    spec:
      name: string
      namespace: string | default="default"
      image: string | default="dogsvscats/worker:latest"
      replicas: integer | default=1
      redisEndpoint: string
      postgresEndpoint: string
      postgresSecretName: string
    status:
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}

  resources:
  - id: deployment
    readyWhen:
      - ${deployment.spec.replicas == deployment.status.availableReplicas}
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${schema.spec.name}-worker
        namespace: ${schema.spec.namespace}
        labels:
          app.kubernetes.io/name: ${schema.spec.name}-worker
          app: ${schema.spec.name}-worker
      spec:
        replicas: ${schema.spec.replicas}
        selector:
          matchLabels:
            app.kubernetes.io/name: ${schema.spec.name}-worker
            app: ${schema.spec.name}-worker
        template:
          metadata:
            labels:
              app.kubernetes.io/name: ${schema.spec.name}-worker
              app: ${schema.spec.name}-worker
          spec:
            containers:
            - name: worker
              image: ${schema.spec.image}
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              env:
              - name: REDIS_HOST
                value: ${schema.spec.redisEndpoint}
              - name: POSTGRES_HOST
                value: ${schema.spec.postgresEndpoint}
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${schema.spec.postgresSecretName}
                    key: password
              - name: POSTGRES_DB
                value: postgres
            restartPolicy: Always